// <auto-generated />
using System;
using GestorCredito.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorCredito.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926052551_AgregarPagoCuotaYRolCajero")]
    partial class AgregarPagoCuotaYRolCajero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorCredito.Api.Models.CuentaBancariaInterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Moneda")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId", "NumeroDocumento", "NumeroCuenta")
                        .IsUnique()
                        .HasDatabaseName("IX_CuentaBancariaInterna_Cliente_NumeroCuenta");

                    b.ToTable("CuentasBancariasInternas");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amortizacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaPagoRealizado")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<decimal>("Otros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pagada")
                        .HasColumnType("bit");

                    b.Property<decimal>("PagoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SimulacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SimulacionId");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.DeclaracionInversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoInvertir")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrigenFondos")
                        .HasColumnType("int");

                    b.Property<int>("ProspectoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProspectoId")
                        .IsUnique();

                    b.ToTable("DeclaracionesInversion");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.DocumentoAdjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProspectoId")
                        .HasColumnType("int");

                    b.Property<int>("RequisitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequisitoId");

                    b.HasIndex("ProspectoId", "RequisitoId")
                        .IsUnique();

                    b.ToTable("DocumentosAdjuntos");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.DocumentoGenerado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProspectoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProspectoId");

                    b.ToTable("DocumentosGenerados");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CargoOtrosPorCuota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiaPago")
                        .HasColumnType("int");

                    b.Property<int>("FrecuenciaPago")
                        .HasColumnType("int");

                    b.Property<int>("Moneda")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PlazoMax")
                        .HasColumnType("int");

                    b.Property<int>("PlazoMin")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereDeclaracionInversion")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiereRequisitos")
                        .HasColumnType("bit");

                    b.Property<decimal>("TasaMax")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TasaMin")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos", t =>
                        {
                            t.HasCheckConstraint("CK_Producto_MontoMax", "[MontoMax] >= [MontoMin]");

                            t.HasCheckConstraint("CK_Producto_MontoMin", "[MontoMin] > 0");

                            t.HasCheckConstraint("CK_Producto_PlazoRango", "[PlazoMax] >= [PlazoMin] AND [PlazoMin] >= 1");

                            t.HasCheckConstraint("CK_Producto_TasaRango", "[TasaMax] >= [TasaMin] AND [TasaMin] >= 0");
                        });
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Prospecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ComentarioAprobador")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("CuentaBancariaInternaId")
                        .HasColumnType("int");

                    b.Property<string>("CuentaExternaBanco")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CuentaExternaCCI")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ResultadoMock")
                        .HasColumnType("int");

                    b.Property<int?>("TipoCuentaDesembolso")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuentaBancariaInternaId");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("IX_Prospecto_NumeroDocumento_Activo")
                        .HasFilter("[Estado] IN (0, 1, 2, 3, 5)");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Prospectos");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Requisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Requisitos");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Simulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aceptada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSimulacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Plazo")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ProspectoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProspectoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Simulacion_ProspectoId_Aceptada")
                        .HasFilter("[Aceptada] = 1");

                    b.ToTable("Simulaciones");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.TipoPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposPersona");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TipoDocumentoTipoPersona", b =>
                {
                    b.Property<int>("TiposDocumentoId")
                        .HasColumnType("int");

                    b.Property<int>("TiposPersonaId")
                        .HasColumnType("int");

                    b.HasKey("TiposDocumentoId", "TiposPersonaId");

                    b.HasIndex("TiposPersonaId");

                    b.ToTable("TipoDocumentoTipoPersona", (string)null);
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Cuota", b =>
                {
                    b.HasOne("GestorCredito.Api.Models.Simulacion", "Simulacion")
                        .WithMany("Cuotas")
                        .HasForeignKey("SimulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacion");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.DeclaracionInversion", b =>
                {
                    b.HasOne("GestorCredito.Api.Models.Prospecto", "Prospecto")
                        .WithOne("DeclaracionInversion")
                        .HasForeignKey("GestorCredito.Api.Models.DeclaracionInversion", "ProspectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prospecto");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.DocumentoAdjunto", b =>
                {
                    b.HasOne("GestorCredito.Api.Models.Prospecto", "Prospecto")
                        .WithMany("DocumentosAdjuntos")
                        .HasForeignKey("ProspectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorCredito.Api.Models.Requisito", "Requisito")
                        .WithMany()
                        .HasForeignKey("RequisitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prospecto");

                    b.Navigation("Requisito");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.DocumentoGenerado", b =>
                {
                    b.HasOne("GestorCredito.Api.Models.Prospecto", "Prospecto")
                        .WithMany("DocumentosGenerados")
                        .HasForeignKey("ProspectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prospecto");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Prospecto", b =>
                {
                    b.HasOne("GestorCredito.Api.Models.CuentaBancariaInterna", "CuentaBancariaInterna")
                        .WithMany()
                        .HasForeignKey("CuentaBancariaInternaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestorCredito.Api.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestorCredito.Api.Models.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CuentaBancariaInterna");

                    b.Navigation("Producto");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Requisito", b =>
                {
                    b.HasOne("GestorCredito.Api.Models.Producto", "Producto")
                        .WithMany("Requisitos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Simulacion", b =>
                {
                    b.HasOne("GestorCredito.Api.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorCredito.Api.Models.Prospecto", "Prospecto")
                        .WithMany("Simulaciones")
                        .HasForeignKey("ProspectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Prospecto");
                });

            modelBuilder.Entity("TipoDocumentoTipoPersona", b =>
                {
                    b.HasOne("GestorCredito.Api.Models.TipoDocumento", null)
                        .WithMany()
                        .HasForeignKey("TiposDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorCredito.Api.Models.TipoPersona", null)
                        .WithMany()
                        .HasForeignKey("TiposPersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Producto", b =>
                {
                    b.Navigation("Requisitos");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Prospecto", b =>
                {
                    b.Navigation("DeclaracionInversion");

                    b.Navigation("DocumentosAdjuntos");

                    b.Navigation("DocumentosGenerados");

                    b.Navigation("Simulaciones");
                });

            modelBuilder.Entity("GestorCredito.Api.Models.Simulacion", b =>
                {
                    b.Navigation("Cuotas");
                });
#pragma warning restore 612, 618
        }
    }
}
